# Use root/example as user/password credentials
version: '3.1'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    logging:
      driver: syslog
      options:
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/nginx:/etc/nginx/conf.d
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  adminer:
    image: adminer
    restart: always
  nextjs:
    build: 
      context: ./food-review
      args:
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        DB_HOST: postgres
        SECRET_KEY: ${SECRET_KEY}
